language: python
python:
  - "3.4"
# command to install dependencies
install: 
- "pip install -U pip"
- "pip install -U pandas scikit-learn numpy matplotlib nbconvert jupyter_client ipykernel"
- "pip install -U imblearn"
- "pip install -U mlxtend"
# command to run tests
script: jupyter-nbconvert --execute hw3_starter_notebook.ipynb



